# Generated by Django 3.2.8 on 2021-10-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='pun_data',
            new_name='pub_date',
        ),
    ]
